function [ statistic_channel_matrix ] = calculateChannelMatrix( rician_factor,...
            carrier_lambda,statistic_number,statistic_locate,...
            cluster_average_power,cluster_number,observation_radius,...
            cluster_locate,transmit_antenna_number,transmit_delta,...
            transmit_phi,receiver_antenna_number,receiver_array_beta,...
            receiver_delta )
%input rician_factor：赖斯因子
%      carrier_lambda：载波波长
%      statistic_number：统计信息个数
%      statistic_locate：统计点位置
%      cluster_average_power：散射体平均功率
%      cluster_number：散射体数量
%      cluster_locate：散射体位置
%      transmit_antenna_number：发射端天线个数
%      transmit_delta：发射端天线间距
%      transmit_phi：发射初始相位
%      receiver_antenna_number：接收端天线个数
%      receiver_array_beta：接收端天线接收角
%      receiver_delta：接收端天线间距
%output statistic_channel_matrix：各个用户的信道矩阵，前两个维度为信道矩阵，第三个维度为用户索引
    statistic_channel_matrix = zeros(receiver_antenna_number,...
        transmit_antenna_number,statistic_number);
    for i = 1:statistic_number
        for j = 1:transmit_antenna_number
            for k = 1:receiver_antenna_number
                %视距部分计算
                statistic_channel_matrix(k,j,i) = LOS( statistic_locate(i,:),...
                    j,transmit_antenna_number,transmit_delta,transmit_phi,...
                    k,receiver_antenna_number,receiver_delta,receiver_array_beta,...
                    carrier_lambda,rician_factor );
                for n = 1:cluster_number
                    if (statistic_locate(j,1) - cluster_locate(n,1)) ^ 2 +...
                            (statistic_locate(j,2) - cluster_locate(n,2)) ^ 2 <=...
                            observation_radius ^ 2 && cluster_locate(n,1) ^ 2 +...
                            cluster_locate(n,2) ^ 2 <=observation_radius ^ 2
                        %非视距部分计算
                        statistic_channel_matrix(k,j,i) = statistic_channel_matrix(k,j,i) + NLOS(cluster_average_power,...
                            rician_factor,cluster_number,statistic_locate(i,:),...
                            j,transmit_antenna_number,transmit_delta,k,...
                            receiver_antenna_number,receiver_delta,...
                            receiver_array_beta,cluster_locate(n,:),...
                            transmit_phi,carrier_lambda);
                    end
                end
            end
        end
    end
end

